### ISSUE TITLE
Probleme Beim spiel Beitritt 

### ISSUE THREAD

**Issue by Marlon44585** [AMacro/dv-multiplayer#50]
Probleme Beim spiel Beitritt beim conectet dann Mann nach dem ich auf verbinden gedrückt habe dann kommt attempt 1 und dann attempt 2 und dann passiert nichts mehr auch bei der Person die gehostet hat

**Comment by AMacro** [comment]
> Probleme Beim spiel Beitritt beim conectet dann Mann nach dem ich auf verbinden gedrückt habe dann kommt attempt 1 und dann attempt 2 und dann passiert nichts mehr auch bei der Person die gehostet hat

In their router, the host will need to forward a port (IPv4) or open a port (IPv6). The default port is 7777, but others can be used (I use 4296).

You will need to find instructions specific to the hosts' router.

In the future, we hope to add features so this is no longer a requirement.

Der Host muss in seinem Router einen Port weiterleiten (IPv4) oder öffnen (IPv6). Der Standardport ist 7777, es können aber auch andere verwendet werden (ich verwende 4296).

Sie müssen spezifische Anweisungen für den Router des Hosts finden.

Wir hoffen, in der Zukunft Funktionen hinzufügen zu können, sodass dies keine Anforderung mehr ist.
