### ISSUE TITLE
Clients stuck in "Sync Data" Loading Screen

### ISSUE THREAD

**Issue by fynnlem** [AMacro/dv-multiplayer#51]
Hello Guys,

When clients try to join me, they get stuck in "Synchronize data". For me as the host it shows that they are joined, they are stuck in the loading screen until I close the game.

(translated by Google)

please Help guys, we have this problem since 1 Month

**Comment by fynnlem** [comment]
we had this issue in 0.1.8.2 and in 0.1.8.3

**Comment by AMacro** [comment]
> Hello Guys,
> 
> When clients try to join me, they get stuck in "Synchronize data". For me as the host it shows that they are joined, they are stuck in the loading screen until I close the game.
> 
> (translated by Google)
> 
> please Help guys, we have this problem since 1 Month

Hi @fynnlem,

Are you or the other clients using any other mods?

Are you able to post both the server/host `player.log` and at least 1 client `player.log`?

The log files can be found by copying this location and pasting into either the run dialogue (Win Key + R) or pasting into the address bar in Windows Explorer: `%appdata%\..\LocalLow\Altfuture\Derail Valley`

**Comment by fynnlem** [comment]
Yeah i send them later. The only other mod i use ist the Remote dispatcher

**Comment by fynnlem** [comment]
Hello,

I reinstalled the game and its working now.

Thanks for your help anyway!

(my english is very bad)
