### ISSUE TITLE
Derail Valley multiplayer not booting in DV B99

### ISSUE THREAD

**Issue by Atores1** [AMacro/dv-multiplayer#53]
Today I tried to install the multiplayer mod in Derail Valley B99 and after the install it have not booted. In the log this caught my eye

`Failed to load types in assembly 'Multiplayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Ludiq.TypeUtility+<GetTypesSafely>d__35.MoveNext () [0x00017] in <afc846f684364b38be7b9624a972dc39>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)`

[Player.log](https://github.com/user-attachments/files/17880099/Player.log)

Is there any way to fix it? I would like to play with my friends, thank you very much.

**Comment by AMacro** [comment]
Hi @Atores1,

B99 has made some big changes and we are currently working on providing an update - an alpha version is available on [Discord](https://discord.com/channels/332511223536943105/1234574186161377363/1309501906896551967), but we should be releasing it on GitHub soon.

**Comment by AMacro** [comment]
Fixed in [0.1.9.0](https://github.com/AMacro/dv-multiplayer/releases/tag/v0.1.9.0-Beta)
